version: '3.8'
services:
  api:
    build:
      context: ./test_task_shramko
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./test_task_shramko/:/usr/src/api/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
